# Generated by Django 5.2 on 2025-04-03 11:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='ReplacementOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_type', models.CharField(choices=[('washing_machine', 'Washing Machine'), ('dishwasher', 'Dishwasher'), ('refrigerator', 'Refrigerator'), ('oven', 'Oven'), ('microwave', 'Microwave')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('efficiency', models.CharField(choices=[('good', 'Good'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('matching_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('washing_machine', 'Washing Machine'), ('dishwasher', 'Dishwasher'), ('refrigerator', 'Refrigerator'), ('oven', 'Oven'), ('microwave', 'Microwave')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('usage', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('within_warranty', models.BooleanField(default=False)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='assets.flat')),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='assets.property'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('delivery_date', models.DateField()),
                ('delivery_time_hour', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('delivery_time_minute', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notification_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='assets.flat')),
                ('old_appliance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_orders', to='assets.appliance')),
                ('replacement_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.replacementoption')),
            ],
        ),
    ]
