# Generated by Django 5.2 on 2025-04-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='user_profiles/')),
            ],
        ),
        migrations.AddField(
            model_name='appliance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='appliance_images/'),
        ),
    ]
