# Generated by Django 5.2 on 2025-04-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_user_appliance_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replacementoption',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='appliance',
            name='image',
            field=models.ImageField(blank=True, default='default_images/default_appliance.jpg', null=True, upload_to='appliance_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_images/default_profile.jpg', null=True, upload_to='user_profiles/'),
        ),
    ]
